 #FinancialForce.com, inc. claims copyright in this software, its screen display designs and
 #supporting documentation. FinancialForce and FinancialForce.com are trademarks of FinancialForce.com, inc.
 #Any unauthorized use, copying or sale of the above may constitute an infringement of copyright and may
 #result in criminal or other legal proceedings.
 #Copyright FinancialForce.com, inc. All rights reserved.
###################################################
# Apps  
###################################################
$accounting = "Accounting"
$billing = "Billing"
$salesforcechatter = "Salesforce Chatter"
###################################################
# Tabs  
###################################################
$tab_accounting_currencies = "Accounting Currencies"
$tab_accounting_summarization = "Accounting Summarization"
$tab_allocation_template = "Allocation Templates"
$tab_accounts = "Accounts"
$tab_aged_analysis_definitions = "Aged Analysis Definitions"
$tab_aged_analysis_reports = "Aged Analysis Reports"
$tab_allocations = "Allocations"
$tab_allocation_scheduler = "Allocation Scheduler"
$tab_allocation_templates = "Allocation Templates"
$tab_app_launcher = "App Launcher"
$tab_archive_set="Archive Sets"
$tab_as_of_aging = "As of Aging"
$tab_background_matching = "Background Matching"
$tab_background_posting_scheduler = "Background Posting Scheduler"
$tab_balance_update = "Balance Update"
$tab_bank_accounts = "Bank Accounts"
$tab_bank_reconciliation_line_items = "Bank Reconciliation Line Items"
$tab_bank_statements = "Bank Statements"
$tab_basedatajob = "BaseDataJob"
$tab_budgets_and_balances = "Budgets and Balances"
$tab_cache_management = "Cache Management"
$tab_cash_entries = "Cash Entries"
$tab_cash_matching = "Cash Matching"
$tab_chatter = "Chatter"
$tab_companies = "Companies"
$tab_contacts = "Contacts"
$tab_currency_revaluations = "Currency Revaluations"
$tab_dataviews = "Dataviews"
$tab_dimension_1 = "Dimension 1"
$tab_dimension_2 = "Dimension 2"
$tab_dimension_3 = "Dimension 3"
$tab_dimension_4 = "Dimension 4"
$tab_documents = "Documents"
$tab_export_action_views = "Export Action Views"
$tab_inquiry_template = "Action View Templates"
$tab_general_ledger_accounts = "General Ledger Accounts"
$tab_home = "Home"
$tab_import_action_views = "Import Action Views"
$tab_income_schedule_definitions = "Income Schedule Definitions"
$tab_input_form_manager = "Input Form Manager"
$tab_integration_rules = "Integration Rules"
$tab_intercompany_definitions = "Intercompany Definitions"
$tab_intercompany_transfers = "Intercompany Transfers"
$tab_transaction_reconciliations = "Transaction Reconciliation"
$tab_intersect_definitions = "Intersect Definitions"
$tab_journals = "Journals"
$tab_mass_email = "Mass Email"
$tab_merge_accounts = "Merge Accounts"
$tab_online_inquiries = "Action Views"
$tab_opportunities = "Opportunities"
$tab_orders = "Orders"
$tab_payable_credit_notes = "Payable Credit Notes"
$tab_payable_invoices = "Payable Invoices"
$tab_payments = "Payments"
$tab_new_payment = "Payments Plus"
$tab_payment_selection = "Payment Selection"
$tab_payment_templates = "Payment Templates"
$tab_periods = "Periods"
$tab_price_book = "Price Books"
$tab_products = "Products"
$tab_profile = "Profile"
$tab_record_lock_groups = "Record Lock Groups"
$tab_record_locks = "Record Locks"
$tab_related_content_panes = "Related Content Panes"
$tab_reporting_balances = "Reporting Balances"
$tab_reporting_balance_update = "Reporting Balance Update"
$tab_reports = "Reports"
$tab_run_Integration_rule = "Run Integration Rule"
$tab_select_palette_sections = "Select Palette Sections"
$tab_sales_credit_notes = "Sales Credit Notes"
$tab_sales_invoices = "Sales Invoices"
$tab_sales_tax_calculation_settings = "External Tax Calculation Settings"
$tab_select_company = "Select Company"
$tab_selection_definitions = "Selection Definitions"
$tab_sub_analysis_mapping = "Sub-Analysis Mapping"
$tab_summarization_template = "Summarization Templates"
$tab_tax_codes = "Tax Codes"
$tab_text_definitions = "Text Definitions"
$tab_transaction_line_items = "Transaction Line Items"
$tab_transactions = "Transactions"
$tab_user_companies = "User Companies"
$tab_workers= "Workers"
$tab_years = "Years"
$tab_bank_reconciliations = "Bank Reconciliations"
$tab_all_tabs_locator = "a[href*='showAllTabs']"
$tab_chart_of_accounts_mappings = "Chart of Accounts Mappings"
$tab_community_myaccounts = "MyAccount"
$tab_bank_lockboxes = "Bank Lockboxes"
$tab_ar_cash_transaction = "AR Cash Transactions"
$tab_consolidated_invoices = "Consolidated Invoices"
$tab_google_connector = "Google Connector"
$tab_dsm_mappings = "DSM Mappings"
$tab_opportunity_to_sales_agreement_mappings = "Opportunity to Sales Agreement Mappings"

$tab_psa_config = "PSA Administration"
$tab_work_calendars = "Work Calendars"
$tab_regions = "Regions"
$tab_permission_controls = "Permission Controls"
$tab_projects = "Projects"
$tab_milestones = "Milestones"
$tab_billing_event_generation = "Billing Event Generation"
$tab_vendor_invoices = "Vendor Invoices"
$tab_configuration_groups= "Configuration Groups"
$tab_billing_events  = "Billing Events"
$tab_transaction_reconciliations = "Transaction Reconciliations"
$tab_chart_of_accounts_structures = "Chart of Accounts Structures"
$tab_sales_orders = "Sales Orders"
$tab_sales_order_quick_start ="Sales Order QuickStart"
$tab_bank_format_definitions = "Bank Format Definitions"
$tab_bank_format_mappings = "Bank Format Mappings"
$tab_bank_format_export_import = "Bank Format Export/Import"
$tab_statistical_value = "Statistical Bases"
$tab_allocation_rules = "Allocation Rules"
$tab_settings = "Settings"
$tab_recognition_years = "Recognition Years"
$tab_recognize_revenue = "Recognize Revenue"
$tab_avalara_settings = "Avalara Settings"
$tab_avalara_tax_mappings = "Avalara Tax Mappings"
$tab_scm_product_mappings = "SCM Product Mappings"
$tab_product_groups = "Product Groups"
$tab_action_queues = "Action Queues"
$tab_inventory_network = "Inventory Network"
$tab_payment_detail_templates = "Payment Details Templates"
$tab_billing_documents = "Billing Documents"
$tab_dfp_configuration = "DFP Report Configuration"
$tab_dfp_reports = "DFP Reports"
###################################################
# ffa companies 
###################################################
$company_apex_comp_eur = "Apex Company EUR" 
$company_merlin_auto_aus = "Merlin Auto AUS" 
$company_merlin_auto_gb = "Merlin Auto GB" 
$company_merlin_auto_spain = "Merlin Auto Spain" 
$company_merlin_auto_usa = "Merlin Auto USA" 
$company_merlin_tech_us = "MerlinTech US" 
###################################################
# ffa custom settings
###################################################
$ffa_custom_setting_accounting_settings = "Accounting Settings (FF)"
$ffa_custom_setting_srp_integration_settings = "SRP Integration Settings"
$ffa_custom_setting_as_of_aging_report_settings = "As of Aging Report Settings"
$ffa_custom_setting_tab_default_off = "Default Off"
$ffa_custom_setting_tab_default_on = "Default On"
$ffa_custom_setting_tab_tab_hidden = "Tab Hidden"
$ffa_edit_enabled_visualforce_page_access = "//h3[text()='Enabled Visualforce Page Access']/ancestor::td/following-sibling::td/input"
$ffa_custom_setting_srp_company_source_input = "input[id$='CompanySource__c']"
$ffa_custom_setting_srp_misc_adjustment_balance_gla_code_input = "input[id$='MiscAdjustmentBalancingGLACode__c']"
###################################################
# FFa custom setting property names
###################################################
# Accounting Settings (FF)
$ffa_accounting_settings_override_currency_values = "Override Currency Values on Journal Line"
$ffa_accounting_settings_enable_edit_dimensions_after_posting = "Enable Edit Dimensions (after posting)"
$ffa_accounting_settings_gla_filtering_payment_selection = "GLA Filtering in Payment Selection"
$ffa_accounting_settings_disable_vendor_number_check = "Disable Vendor Document Number Check"
$ffa_accounting_settings_duplicate_vendor_number_allowed = "Duplicate Vendor Document Number Allowed"
$ffa_accounting_settings_sales_invoice_lines_threshold = "Sales Invoice Lines Threshold"
$ffa_accounting_settings_profitability_report_id = "Profitability Report ID"
###################################################
# Labels
###################################################
$label_product_line_quantity= "Quantity"
$label_product_line_unit_price = "Unit Price"
$label_product_line_net_value = "Net Value"
$label_trx_line_type_account = "Account"
$label_crv_dual_exchange_rate = "Dual Exchange Rate"
$label_crv_status = "Status"
$label_crv_currency_revaluation_name ="Currency Revaluation Name"
$label_credit_note_number = "Credit Note Number"
$label_sales_tax_status = "External Tax Status"
$label_credit_note_status = "Credit Note Status"
$label_invoice_currency = "Invoice Currency"
$label_vendor_invoice_total = "Vendor Invoice Total"
$label_discard_reason = "Discard Reason"
$label_reference1 = "Reference 1"
$label_credit_note_reason = "Credit Note Reason"
$label_credit_note_currency = "Credit Note Currency"
$label_vendor_credit_note_total = "Vendor Credit Note Total"
$label_invoice_number = "Invoice Number"
$label_invoice_status = "Invoice Status"
$label_invoice_total = "Invoice Total"
$label_payable_invoice_number = "Payable Invoice Number"
$label_vendor_invoice_number = "Vendor Invoice Number"
$label_vendor_credit_note_number = "Vendor Credit Note Number"
$label_payment_selection_due_date = "Due Date"
$label_payment_outstanding_value = "Outstanding Value"
$label_payment_gross_value = "Gross Value"
$label_payment_discount = "Discount"
$label_payment_payment_value = "Payment Value"
$label_status = "Status"
$label_payment_number = "Payment Number"
$label_payment_cancel_reason = "Cancel Reason"
$label_payment_media_check = "Check"
$label_cashentry_number = "Cash Entry Number"
$label_cashentry_status = "Status"
$label_bank_statement_status = "Status"
$label_newpayment_details_text_indication = "Define when and how you are going to pay"
$label_newpayment_date = "Payment Date"
$label_newpayment_bank_account = "Bank Account"
$label_newpayment_currency = "Payment Currency"
$label_newpayment_media_check = "Payment Method"
$label_newpayment_discounts_text_indication = "Add general ledgers accounts (GLAs) for settlement discounts and currency write-offs"
$label_newpayment_settlement_discount = "Settlement Discount"
$label_newpayment_show_dimensions = "Show Dimensions"
$label_newpayment_hide_dimensions = "Hide Dimensions"
$label_newpayment_settlement_discount_dim1 = "Dimension 1"
$label_newpayment_settlement_discount_dim2 = "Dimension 2"
$label_newpayment_settlement_discount_dim3 = "Dimension 3"
$label_newpayment_settlement_discount_dim4 = "Dimension 4"
$label_newpayment_currency_write_off = "Currency Write-off"
$label_newpayment_write_off_dim1 = "Dimension 1"
$label_newpayment_write_off_dim2 = "Dimension 2"
$label_newpayment_write_off_dim3 = "Dimension 3"
$label_newpayment_write_off_dim4 = "Dimension 4"
$label_newpayment_status = "Status"
$label_newpayment_payment_total = "Payment Total"
$label_newpayment_document_proposed = "Transactions Proposed"
$label_newpayment_vendors_proposed = "Vendors Proposed"
$label_bank_account = "Bank Account"
$label_newpayment_trans_sel_due_date = "Due Date"
$label_newpayment_trans_sel_GLA = "Accounts Payable Control GLA"
$label_newpayment_trans_sel_inv_number = "Payable Invoice Number"
$label_newpayment_trans_sel_pay_method = "Vendor Payment Method"
$label_newpayment_trans_sel_vendor_inv_number = "Vendor Invoice Number"
$label_newpayment_trans_sel_vendor_name = "Vendor Name"
$label_standard_pricebook = "Standard"
$label_cash_entry_reference = "Reference"
$label_journal_number = "Journal Number"
$label_journal_reference = 'Reference'
$ffa_label_feed_tracking = "Feed Tracking"
$label_credit_note_total = "Credit Note Total"
$ffa_label_tab_label = "Tab Label"
$ffa_label_tab_name = "Tab Name"

###################################################
# ffa messages alias
###################################################
$ffa_msg_loading = "Loading"
$ffa_msg_exporting= "Exporting"
$ffa_msg_loading_sencha = "Loading..."
$ffa_msg_loading_metadata = "Loading metadata"
$ffa_msg_saving = "Saving"
$ffa_msg_saved_successfully = "Saved successfully."
$ffa_msg_saving_your_settings = "Saving your settings"
$ffa_msg_updating_due_date_and_period = "Updating Due Date and Period"
$ffa_msg_calculating_due_date_and_period = "Calculating Due Date and Period"
$ffa_msg_loading_dataview = "Loading dataview"
$ffa_msg_retrieving_account_information = "Retrieving Account Information"
$ffa_msg_retrieving_bank_account_information = "Retrieving Bank Account Information" 
$ffa_msg_updating_taxrate_duedate_period  = "Updating Tax Rate, Due Date and Period"
$ffa_msg_updating_taxrate = "Updating Tax Rate"
$ffa_msg_adding_line = "Adding Line"
$ffa_msg_working = "Working"
$ffa_msg_calculating_value = "Calculating Value"
$ffa_msg_calculating_tax_value = "Calculating Tax Value"
$ffa_msg_processing_reverse_charge = "Processing Reverse Charge"
$ffa_msg_removing_line = "Removing Line"
$ffa_msg_calculating_tax = "Calculating Tax"
$ffa_msg_calculating_line = "Calculating Line"
$ffa_msg_updating_income_schedule = "Updating Income Schedule"
$ffa_msg_changing_currency = "Changing Currency"
$ffa_msg_feed_tracking_saved_successfully = "Your changes have been saved"
$ffa_msg_executing_background_posting = "Background posting executing now."
$ffa_msg_creating_invoice = "You are about to create an invoice. Do you want to continue?"
$ffa_msg_ict_process_confirmation = "You are about to process an intercompany transfer. Do you want to continue?"
$ffa_msg_sin_amend_document_warning = "Any amendments that you make to a complete source sales invoice will not be passed on to the destination payable invoice"
$ffa_msg_scr_amend_document_warning = "Any amendments that you make to a complete source sales credit note will not be passed on to the destination payable credit note."
$ffa_msg_getting_templates = "Getting Templates"
$ffa_msg_updating_payment_schedule_fields = "Updating Payment Schedule Fields"
$ffa_msg_calculating_payment_schedule = "Calculating Payment Schedule"
$ffa_payment_schedule_calculate_button = "Calculate"
$ffa_msg_updating_cashentry_currency = "Updating Cash Entry Currency"
$ffa_msg_cashmatching_completed_message = "Cash Matching completed successfully."
$ffa_msg_undocashmatching_completed_message = "Undo Match completed successfully."
$ffa_msg_cashmatching_reference_message = "Cash Matching reference"
$ffa_msg_currency_revaluation_submit_process_information = "currency revaluation documents are being generated with a group name"
$ffa_msg_currency_revaluation_auto_post_process_information = "Successfully generated currency revaluations will automatically be posted and additional emails sent, one per document."
$ffa_msg_balance_update_processing_message = "Balance Update is in progress. You will be notified by email when the process is complete."
$ffa_msg_retrieving_bank_account_information = "Retrieving Bank Account Information"
$ffa_msg_company_activated_successfully = "The company has been activated successfully."
$ffa_msg_calculate_period_confirmation = "You are about to calculate periods for this year. Do you want to continue?"
$ffa_msg_retrieving_period = "Retrieving Period"
$ffa_msg_starting_action = "Starting Action..."
$ffa_msg_retrieving_payment_currency = "Retrieving Payment Currency"
$ffa_msg_updating_payment_date = "Updating payment date"
$ffa_msg_retrieving_accounts = "Retrieving Accounts"
$ffa_msg_multi_company_mode_error = "Company: This operation cannot be performed in multi-company mode."
$ffa_msg_company_not_set_error = "Current company not set."
$ffa_msg_company_changed_error = "Current company has changed."
$ffa_msg_payment_pay_enter_payable_Control_field_value = "The payment process failed. The error must be corrected and the process repeated. For account(s) ["+$sf_param_substitute+"]. You must enter a value in the Account Payable Control field."
$ffa_msg_payment_confirm_pay_enter_payable_Control_field_value = "For account(s) ["+$sf_param_substitute+"]. You must enter a value in the Account Payable Control field."
$ffa_msg_retrieving_bank_charges_gla_information = "Retrieving Bank Charges GLA Information"
$ffa_msg_payment_enter_Receivable_Control_field_value = "The payment process failed. The error must be corrected and the process repeated. For account(s) ["+$sf_param_substitute+"]. You must enter a value in the Account Receivable Control field."
$ffa_msg_loading_transaction_line_detail = "Loading Transaction Line Detail"
$ffa_manage_lines_saving_locator = "//span[text()='Saving']"
$ffa_msg_search_results_ouput_text = $sf_param_substitute+" result(s) found."
$ffa_msg_mass_email_sending_information = "Mass Email sending in progress. You will be notified by email when the process is complete."
$ffa_msg_obj_validation_failed_closed_period_error = "Object validation has failed. You cannot save a document that falls within a closed period"
$ffa_msg_psa_ffa_ir_rule_generate = "FinancialForce PSA and Accounting integration rules created successfully."
$ffa_msg_custom_field_already_present_error_msg = "Error: There is already a field named"
$ffa_msg_import_bank_format_definition_success_message = "The process has completed successfully. Click the Bank Format Definition tab to view the new record."
$ffa_msg_import_bank_format_mapping_success_message = "The process has completed successfully. Click the Bank Format Mapping tab to view the new record."
$ffa_msg_generate_bank_file_succes_message = "This process may take some time to complete. You will be informed by email when it does."
###################################################
# Feed tracking objects
###################################################
$ffa_feedtracking_object_sales_invoice = "codaInvoice"
###################################################
# ffa common 
###################################################
# buttons 
$ffa_post_button = "Post"
$ffa_save_post_button = "Save & Post"
$ffa_discard_button = "Discard"
$ffa_create_invoice_button = "Create Invoice"
$ffa_convert_button = "Convert"
$ffa_classic_view_button = "Classic View"
$ffa_amend_document_button = "Amend Document"
$ffa_manage_line_button = "Manage Lines"
$ffa_post_match = "Post & Match"
$ffa_match = "Match"
$ffa_continue = "Continue"
$ffa_print_pdf_button = "Print PDF"
$ffa_post_invoices_button = "Post Invoices"
$ffa_post_credit_note_button = "Post Credit Notes"
$ffa_reverse_button = "Reverse"
$ffa_run_now_button = "Run Now"
$ffa_calculate_tax_button = "Calculate Tax"
$ffa_Calculate_tax_on_Credit_Notes_button = "Calculate tax on Credit Notes"
$ffa_Calculate_tax_on_invoices_button = "Calculate tax on Invoices"
$ffa_hold_base_data_button = "Hold Base Data"
$ffa_delete_new_data_button = "Delete New Data"
$ffa_place_on_hold_button = "Place on Hold"
$ffa_change_currency_button = "Change Currency"
$ffa_apply_button = "Apply"
$ffa_select_button = "Select"
$ffa_next_button = "Next"
$ffa_add_button = "Add"
$ffa_save_button = "Save"
$ffa_attach_button = "input[id='Attach']"
$ffa_attach_done_button = "input[title='Done']"
$ffa_processing_button_locator = "input[value*='Processing']"
$ffa_saving_button_locator = "input[value*='Saving']"
$ffa_integration_rule_generate_refresh_integration_rules_srp_button = "Generate/Refresh Rules for SRP Integration"
$ffa_vendor_inv_create_pin_pcr_button = "Create Payable Invoice/Credit"
$ffa_vendor_inv_create_pin_pcr_button_list_view = "Create Payable Invoices/Credits"
$ffa_billing_event_create_sin_scr_button = "Create Invoices/Credits"
# checkbox
$ffa_enable_feed_tracking_checkbox = "input[id$='enableTracking']"
#links
$ffa_toggle_exchange_rates_icon = "span[id*=':currencyRates'] span[id$=':expanderContainer']"
$ffa_cross_link_to_delete = "td[id*='Block:lineItemSection:dtLineItems:"+$sf_param_substitute+"'] a[href*='Removing Line']"
$ffa_pricebook_activate_link_pattern = "//span[text()='"+$sf_param_substitute+"']/ancestor::tbody[1]/tr/td[3]/div/a/span[text()='"+$sf_param_substitute+"']"
# sencha screen toolbar
$ffa_toolbar_save = "a[data-ffid =saveButton]"
$ffa_toolbar_save_and_run = "a[data-ffid =saveAndRunButton]"
$ffa_toolbar_save_and_build = "a[data-ffid=saveAndBuildButton]"
$ffa_toolbar_edit = "a[data-ffid=editButton]"
$ffa_toolbar_clone = "a[data-ffid = cloneButton]"
$ffa_toolbar_back_to_list = "a[data-ffid = backButton]"
$ffa_toolbar_full_screen = "a[data-ffid=goFullScreen]"
#sencha screen checkbox class
$ffa_sencha_selected_checkbox_class = "f-form-cb-checked"

# objects  
$page_empty_div = "div.multiforce"
$page_spinning_message = "span#indicatortext"
$page_loadmask_message = "div[data-ffxtype=loadmask]"
$page_vf_success_panel = "div.pbSuccess" 
$page_vf_error_panel = "div.pbError"
$page_vf_error_panel2 = "div[class='message errorM3']"
$page_vf_message_text = "div.messageText"
$page_vf_information_text = "div.informationArea"
$page_all_check_box = "allBox"
$page_grid_rows = "div[class*=x-grid3-row]" # salesforce listview 
$page_grid_columns = "tr[class*='x-grid3-hd-row'] td" # salesforce listview
$page_grid_row_pattern = "#ext-gen11 div:nth-of-type("+$sf_param_substitute+") tr td:nth-of-type("+$sf_param_substitute+")"
$page_grid_select_checkbox_pattern = "#ext-gen11 div:nth-of-type("+$sf_param_substitute+") tr td:nth-of-type(1)"
$page_sencha_popup = "div[data-ffxtype=messagebox]"
$page_sencha_popup_close = "img[class*='tool-close']"
$page_sencha_popup_error_message = $page_sencha_popup +" "+ "[data-ffxtype=component][id*=messagebox]"
$page_sencha_popup_warning_message = $page_sencha_popup +" "+ "[data-ffxtype=component][id*=messagebox]"
$page_sencha_popup_success_message = $page_sencha_popup +" "+ "[data-ffxtype=component][id*=messagebox]"
$page_sencha_popup_continue = "a[data-ffid=ok]"
$page_sencha_popup_ok = "a[data-ffid=ok]"
$page_sencha_popup_cancel = "a[data-ffid=cancel]"
$page_sencha_popup_no = "a[data-ffid=no]"
$page_sencha_popup_yes = "a[data-ffid=yes]"
$page_checkbox_checked_class = "[class*='f-form-cb-checked']"
$page_vf_table = "table[class=x-grid3-row-table]"
$page_vf_table_rows = $page_vf_table+" "+"tr"
$page_invalid_field = "input[class*='f-form-invalid-field']:not([data-errorqtip=''])"
$page_text_message = "div[class*='messageText']"
$page_info_box = "div.infoM3"
$page_error_box = "div.errorM3"
$page_feed_tracking_save = "span[id$='saveText']"
$page_title =  "html.ext-strict head title"
$page_heading = "h1.pageType"
$page_grid_select_checkbox_pattern = "#ext-gen11 div:nth-of-type("+$sf_param_substitute+") tr td:nth-of-type(1) div input"
$page_grid_row_checkbox = "//div[@id = 'ext-gen11']/div//table/tbody/tr//*[span='"+$sf_param_substitute+"']/../../preceding-sibling::td[contains(@class,'checkbox')]//input"
$page_waiting_icon = "div.waitingIcon"
$page_grid_edit_link_pattern = "#ext-gen11 div:nth-of-type("+$sf_param_substitute+") tr td:nth-of-type(3) div a:nth-of-type(1)"
#toggle icon
$account_toggle_icon = "span[title='Toggle Analysis area']"
$product_note_analysis_toggle_icon_input = "span[id*='dtLineItems"
$product_note_analysis_toggle_icon_input_end = "'][title='Toggle Notes and Analysis area']"
$currency_toggle_exchange_rate_icon = "span[id$='currencyRates'] img"

# Lookup Objects
$lookup_results_table_rows = "div[class*='lookupBlock'] tr"
$lookup_company_column_pattern=$lookup_results_table_rows + ":nth-of-type("+$sf_param_substitute+") td:nth-of-type(6)"
$lookup_period_column_pattern=$lookup_results_table_rows + ":nth-of-type("+$sf_param_substitute+") th:nth-of-type(1) a"
$lookup_year_company_column_pattern=$lookup_results_table_rows + ":nth-of-type("+$sf_param_substitute+") td:nth-of-type(1)"
$lookup_year_column_pattern=$lookup_results_table_rows + ":nth-of-type("+$sf_param_substitute+") th:nth-of-type(1) a"
$currency_lookup_element = "//td[text()='"+$sf_param_substitute+"']/../th/a"
$lookup_bank_account_pattern = "//td[text()='"+$sf_param_substitute+"']/preceding-sibling::th[1]/a"
$lookup_search_frame = "searchFrame"
$lookup_result_frame = "resultsFrame"
$lookup_search_text = "lksrch"
$lookup_search_frame_title = "frame[title='Search']"
$lookup_search_result= "div[class='srch']"
$lookup_search_frame_lookup_text = "Lookup"
$ffa_account_lookup = "Account Lookup (New Window)"
# Upload files
$upload_file_path='/testUploadFiles/'
###################################################
# ffa select company page  
###################################################
# buttons 
# objects 
$select_company_apex_comp_eur   = "input[id*='dtUserCompanySelector:0']"
$select_company_merlin_auto_aus = "input[id*='dtUserCompanySelector:1']"
$select_company_merlin_auto_gb = "input[id*='dtUserCompanySelector:2']"
$select_company_merlin_auto_spain = "input[id*='dtUserCompanySelector:3']"
$select_company_merlin_auto_usa = "input[id*='dtUserCompanySelector:4']"
$select_company_merlin_tech_us = "input[id*='dtUserCompanySelector:5']"
$select_company_all_checkboxes = "table[id$=dtUserCompanySelector] tbody tr td input"
$select_company_total_num_of_companies= "table[id$=dtUserCompanySelector] tbody tr"
$select_company_company_table= "table[id$=dtUserCompanySelector]"
$select_company_company_name_pattern = "table[id$=':dtUserCompanySelector'] tbody tr:nth-of-type("+$sf_param_substitute+") td:nth-of-type(1) label"
$select_company_company_checkbox_pattern = "table[id$=':dtUserCompanySelector'] tbody tr:nth-of-type("+$sf_param_substitute+") td:nth-of-type(2) input"


#Consolidate Invoice
$consolidated_invoice_convert_to_consolidated_credit_note_button = "Convert to Consolidated Credit Note"
$ffa_integration_rule_generate_integration_rules_button = "Generate Integration Rules"
###################################################
# custom selectors 
###################################################
# custom selector for grid tabs 
Capybara.add_selector(:tab_by_label) do
  xpath {|text| "//span[text()='#{text}']"}
end
Capybara.add_selector(:grid_tab_by_label) do
  xpath {|text| "//span[text()='#{text}']"}
end
Capybara.add_selector(:button_by_label) do
  xpath {|text| "//span[text()='#{text}']"}
end
Capybara.add_selector(:field_by_label) do
  xpath {|text| "//label[text()='#{text}']"}
end
Capybara.add_selector(:div_by_value) do
	xpath {|text| "//div[text()='#{text}']"}
end
Capybara.add_selector(:span_by_label) do
  xpath {|text| "//span[text()='#{text}']"}
end
###################################################
# selection component 
###################################################
# selection componet Objects 
$selection_component_filter_drop_zone  = "label[data-ffxtype=filter-sep]"
$selection_component_filter_drop_zone_edit = "div[data-ffid=filterEdit] span"
$selection_component_filter_drop_zone_delete = "div[data-ffid=filterClose] span"
$selection_component_filter_field = "div[data-ffid=filterFieldSource]"
$selection_component_filter_and = "div[data-ffid=filterAndSource]"
$selection_component_filter_or = "div[data-ffid=filterOrSource]"
###################################################
# filter criteria pop up window 
###################################################
$selection_component_filter_window  = "div[data-ffxtype=filter-editor]"
$selection_component_filter_criteria_field = "[data-ffid=Field] input"
$selection_component_filter_criteria_operator ="[data-ffid=Operator] input"
$selection_component_filter_criteria_value_from = "[data-ffid=fromField] input ,[data-ffid=fromField] textarea"
$selection_component_filter_criteria_value_to = "[data-ffid=toField] input"
$selection_component_filter_criteria_prompt = "div[data-ffxtype=filter-editor] div[data-ffid=Prompt] input"
$selection_component_filter_criteria_ok = "a[data-ffid=applyButton]"
$selection_component_filter_criteria_cancel = "a[data-ffid=cancelButton]"

###################################################
# formula builder component 
###################################################
$formula_component_window  = "div[data-ffid=formulaWindow]"
$formula_component_add_source = $formula_component_window + " "+"div[data-ffid=formulaAddSource]"
$formula_component_subtract_source = $formula_component_window + " "+"div[data-ffid=formulaSubtractSource]"
$formula_component_multiply_source = $formula_component_window + " "+"div[data-ffid=formulaMultiplySource]"
$formula_component_divide_source = $formula_component_window + " "+"div[data-ffid=formulaDivideSource]"
$formula_component_open_bracket_source = $formula_component_window + " "+"div[data-ffid=formulaOpenParenthesisSource]"
$formula_component_close_bracket_source = $formula_component_window + " "+"div[data-ffid=formulaCloseParenthesisSource]"
$formula_component_number_value_source = $formula_component_window + " "+"div[data-ffid=formulaLiteralValueSource]"
$formula_component_field_value_source = $formula_component_window + " "+"div[data-ffid=formulaFieldValueSource]"
$formula_component_column_value_source = $formula_component_window + " "+"div[data-ffid=formulaColumnValueSource]"
$formula_component_number_value_input = $formula_component_window + " "+"[data-ffid=literalNumberFieldEditor]:not([style*=none]) input"
$formula_component_field_value_input= $formula_component_window + " "+ "[data-ffid=FieldEditor]:not([style*=none]) input"
$formula_component_column_value_input = $formula_component_window + " "+"[data-ffid=ColumnEditor]:not([style*=none]) input"

$formula_component_drop_zone  = "div[data-ffid=formulaDropZone] [data-ffxtype=formula-sep]:nth-of-type(nnn)"
$formula_component_drop_zone_text  = "div[data-ffid=formulaDropZone] div[class*=-formula-separator-drop-zone-text]"
$formula_component_drop_zone_first  = "div[data-ffid=formulaDropZone] div[data-ffid=firstSeperator]"
$formula_component_drop_zone_last  = "div[data-ffid=formulaDropZone] div[data-ffid=lastSeperator]"

$formula_component_drop_zone_open_bracket = "[data-ffid=openBracket]"
$formula_component_drop_zone_close_bracket = "[data-ffid=closeBracket]"
$formula_component_decimal_places = $formula_component_window + " "+"[data-ffid=formulaDp] input"
$formula_component_cancel_button = $formula_component_window + " "+"a[data-ffid=cancelButton]"
$formula_component_clear_button = $formula_component_window + " "+"a[data-ffid=clearButton]"
$formula_component_reset_button = $formula_component_window + " "+"a[data-ffid=resetButton]"
$formula_component_ok_button = $formula_component_window + " "+"a[data-ffid=formulaSaveButton]"
$formula_component_error = "[class*=-formula-error]"
$formula_component_column = "div[data-ffxtype=formula-column-value]"
$formula_component_field= "div[data-ffxtype=formula-field-value]"
$formula_component_number = "div[data-ffxtype=formula-literal-value]"
$formula_component_bin = "div[data-ffid=binDropZone]"
$formula_component_container = "div[data-ffxtype=formula-container]"

###################################################
# Sorting and grouping component (inquiry template and online inquries (Action views)
###################################################
$sorting_grouping_items  = "[data-ffxtype=sorting-item]:nth-of-type(nnn)"
$sorting_grouping_area_drop_zone = "div[data-ffid=sortPanel]"
$sorting_grouping_remove  = "a[data-ffid=removeItem] span"
$sorting_grouping_move_up  = "a[data-ffid=moveUp] span"
$sorting_grouping_move_down  = "a[data-ffid=moveDown] span"
$sorting_grouping_field  = "[data-ffid=column] input"
$sorting_grouping_order = "[data-ffid=direction] input"
$sorting_grouping_group = "[data-ffid=group] input"
$sorting_grouping_hide = "[data-ffid=hide] input"
$sorting_grouping_remove_button = "a[data-ffid=removeItem]"
$sorting_grouping_move_up_button = "a[data-ffid=moveUp]"
$sorting_grouping_move_down_button = "a[data-ffid=moveDown]"
$sorting_grouping_add_new_sort_button = "a[data-ffid=addNewSorter]"
$sorting_grouping_clear_sort_button = "a[data-ffid=clearSorters]"
$sorting_grouping_apply_sort_button = "a[data-ffid=applySort]"

###################################################
# Prime documents (common)
###################################################
$doc_line_input = "input[id$='Block:lineItemSection:dtLineItems"
$doc_line_input_end = "']"
$doc_expense_line_input = "input[id*=':dtExpenseLineItems"
# buttons
$doc_new_line_button = "input.newlinebutton"
###################################################
# Page/UI names
###################################################
$label_page_name_sales_credit_note = "Sales Credit Note Detail"
$label_page_name_recurring_invoice = "Recurring Invoices"
###################################################
# Page titles
###################################################
$page_title_sales_invoices_list_view_all = "Sales Invoices"
$page_title_payments_home = "Payments: Home"
##################################################
# FFA Object                                     #
##################################################
$ffa_object_accounts = "Accounts"
$ffa_object_bank_account = "Bank Account"
$ffa_object_intercompany_transfer = "Intercompany Transfer"
$ffa_object_sales_invoice = "Sales Invoice"
$ffa_object_sales_invoice_line_item = "Sales Invoice Line Item"
$ffa_object_sales_invoice_installment_line_item = "Sales Invoice Installment Line Item"
$ffa_object_transaction = "Transaction"
$ffa_object_transaction_line_item = "Transaction Line Item"
$ffa_object_sales_credit_note = "Sales Credit Note"
$ffa_object_sales_credit_note_line_item ="Sales Credit Note Line Item"
$ffa_object_payable_invoice = "Payable Invoice"
$ffa_object_payable_invoice_line_item = "Payable Invoice Line Item"
$ffa_object_payable_invoice_expense_line_item = "Payable Invoice Expense Line Item"
$ffa_object_payable_credit_note = "Payable Credit Note"
$ffa_object_payable_credit_note_expense_line_item = "Payable Credit Note Expense Line Item"
$ffa_object_payable_credit_note_line_item = "Payable Credit Note Line Item"
$ffa_object_payment = "Payment"
$ffa_object_period = "Period"
$ffa_object_cash_entry = "Cash Entry"
$ffa_object_cash_entry_line_item = "Cash Entry Line Item"
$ffa_object_accounting_currency = "Accounting Currency"
$ffa_objects_products= "Products"
$ffa_object_dataview_field= "Dataview Field"
$ffa_object_journal= "Journal"
$ffa_object_journal_line_item = "Journal Line Item"
$ffa_object_dataview_field_locator= "//a[text()='FinancialForce Reporting']/ancestor::tr[1]/th/a[text()='Dataview Field']"
$ffa_object_users = "Users"
$ffa_object_opportunities = "Opportunities"
$ffa_object_sales_agreement = "Sales Agreement"
$ffa_object_sales_agreement_line_item = "Sales Agreement Line Item"
$ffa_object_consolidated_invoice = "Consolidated Invoice"
$ffa_object_integration_rule = "Integration Rule"
$ffa_object_regions = "Region"
$ffa_object_contact = "Contact"
$ffa_object_project = "Project"
$ffa_object_milestone = "Milestone"
$ffa_object_misc_adjustment = "Miscellaneous Adjustment"
$ffa_object_vendor_invoices = "Vendor Invoice"
$ffa_object_billing_event= "Billing Event"
$ffa_object_user_company = "User Company"
$ffa_object_sales_order = "Sales Order"
$ffa_object_revenue_recognition_transaction_line = "Revenue Recognition Transaction Line"
$ffa_object_template= "Template"
$ffa_object_product_group = "Product Group"
$ffa_object_icp= "ICP"
$ffa_object_invoicing = "Invoicing"
##################################################
#Object field Name
##################################################
$ffa_field_line_description = "LineDescription__c"
$ffa_field_apex_class_id = "ApexClassId"
$ffa_field_parent_job_Id = "ParentJobId"
$ffa_field_method_name = "MethodName"
$ffa_field_outcome = "Outcome"
###################################################
# FFA page layout
###################################################
$ffa_sales_invoice_normal_layout = "Sales Invoice Layout"
$ffa_sales_invoice_line_item_normal_layout = "Invoice Line Item Layout"
$ffa_sales_credit_note_normal_layout = "Sales Credit Note Layout"
$ffa_cash_entry_normal_layout= "Cash Entry Layout"
$ffa_sales_credit_note_line_items_normal_layout = "Sales Credit Note Line Item Layout"
$ffa_sales_invoice_extended_layout = 'Sales Invoice Layout (extended)'
$ffa_cash_entry_extended_layout= "Cash Entry Layout (ffcash)"
$ffa_cash_entry_line_item_extended_layout= "Cash Entry Layout (ffcash)"
$ffa_cash_entry_line_item_line_item_normal_layout= "Cash Entry Line Item Layout"
$ffa_cash_entry_line_item_line_item_extended_layout= "Cash Entry Line Item Layout (ffcash)"
$ffa_sales_credit_note_extended_layout ='Sales Credit Note Layout (extended)'
$ffa_invoice_line_item_extended_layout = 'Invoice Line Item Layout (extended)'
$ffa_credit_note_line_item_extended_layout = 'Sales Credit Note Line Item Layout (extended)'
$ffa_purchase_invoice_extended_layout = "Purchase Invoice Layout (extended)"
$ffa_purchase_invoice_line_item_extended_layout = "Purchase Invoice Line Item Layout (extended)"
$ffa_purchase_invoice_expense_line_item_extended_layout = "Purchase Invoice Expense Line Item Layout (extended)"
$ffa_purchase_credit_note_extended_layout = "Purchase Credit Note Layout (extended)"
$ffa_purchase_credit_note_expense_line_item_extended_layout = "Purchase Credit Note Expense Line Item Layout (extended)"
$ffa_purchase_credit_note_line_item_extended_layout = "Purchase Credit Note Line Item Layout (extended)"
$ffa_purchase_invoice_layout = "Purchase Invoice Layout"
$ffa_purchase_credit_note_layout = "Purchase Credit Note Layout"
$ffa_purchase_invoice_expense_line_item_layout = "Purchase Invoice Expense Line Item Layout"
$ffa_purchase_invoice_line_item_layout = "Purchase Invoice Line Item Layout"
$ffa_purchase_credit_note_expense_line_item_layout = "Purchase Credit Note Expense Line Item Layout"
$ffa_purchase_credit_note_line_item_layout = "Purchase Credit Note Line Item Layout"
$ffa_journal_normal_layout= "Journal Layout"
$ffa_journal_line_items_normal_layout = "Journal Line Item Layout"
$ffa_journal_extended_layout= "Journal Layout (extended)"
$ffa_journal_line_items_extended_layout = "Journal Line Item Layout (extended)"
$ffa_account_layout = "Account Layout"
$ffa_bank_layout = "Bank Layout"
$ffa_opportunity_layout = "Opportunity Layout"
$ffa_period_layout = "Period Layout"
$ffa_product_layout = "Product Layout"
$ffa_financialforce_account_layout = "FinancialForce Account Layout"
$ffa_financialforce_product_layout = "FinancialForce Product Layout"
$ffa_home_page_layout_label = "Home Page Layouts"
$ffa_community_home_page_layout = "FinancialForce Home Page Layout (community)"
$ffa_financialforce_user_layout = "User Layout"
$ffa_financialforce_account_media_layout = "Media Account Layout"
$ffa_financialforce_opportunity_media_layout = "FinancialForce Media Opportunity Layout"
$ffa_financialforce_sales_agreement_media_layout = "Sales Agreement Media Layout"
$ffa_financialforce_sales_agreement_line_item_media_layout = "Sales Agreement Line Item Media Layout"
$ffa_financialforce_sales_invoice_media_layout = "Media Sales Invoice Layout"
$ffa_financialforce_sales_invoice_line_item_media_layout = "Media Sales Invoice Line Item Layout"
$ffa_financialforce_sales_credit_note_media_layout = "Media Sales Credit Note Layout"
$ffa_financialforce_sales_credit_note_line_item_media_layout = "Media Sales Credit Note Line Item Layout"
$ffa_financialforce_consolidated_invoice_layout = "Consolidated Invoice Layout"
$ffa_financialforce_integration_rule_list_view_layout = "Integration Rules List View"
$ffa_financialforce_payments_list_view_layout = "Payments List View"
$ffa_financialforce_consolidated_invoice_list_view_layout = "Consolidated Invoices List View"
$ffa_financialforce_vendor_invoice_list_view_layout = "Vendor Invoices List View"
$ffa_financialforce_vendor_invoice_layout = "Vendor Invoice Layout"
$ffa_financialforce_billing_event_layout = "Billing Event Layout"
$ffa_financialforce_transaction_line_item_layout = "Transaction Line Item Layout"
$ffa_financialforce_user_company_layout = "User Company Layout"
###################################################
# Visual force pages
###################################################
$ffa_vf_page_coda_invoice_edit = "codainvoiceedit [#{ORG_PREFIX}codainvoiceedit]"
$ffa_vf_page_coda_invoice_view = "codainvoiceview [#{ORG_PREFIX}codainvoiceview]"
$ffa_vf_page_coda_invoice_new = "codainvoicenew [#{ORG_PREFIX}codainvoicenew]"
$ffa_vf_page_coda_payable_credit_note_edit = "codapurchasecreditnoteedit [#{ORG_PREFIX}codapurchasecreditnoteedit]"
$ffa_vf_page_coda_payable_credit_note_view = "codapurchasecreditnoteview [#{ORG_PREFIX}codapurchasecreditnoteview]"
$ffa_vf_page_coda_payable_credit_note_new = "codapurchasecreditnotenew [#{ORG_PREFIX}codapurchasecreditnotenew]"
$ffa_vf_page_coda_purchase_invoice_new = "codapurchaseinvoicenew [#{ORG_PREFIX}codapurchaseinvoicenew]"
$ffa_vf_page_coda_purchase_invoice_view = "codapurchaseinvoiceview [#{ORG_PREFIX}codapurchaseinvoiceview]"
$ffa_vf_page_coda_purchase_invoice_edit = "codapurchaseinvoiceedit [#{ORG_PREFIX}codapurchaseinvoiceedit]"
$ffa_vf_page_coda_creditnote_edit = "codacreditnoteedit [#{ORG_PREFIX}codacreditnoteedit]"
$ffa_vf_page_coda_creditnote_new = "codacreditnotenew [#{ORG_PREFIX}codacreditnotenew]"
$ffa_vf_page_coda_creditnote_view = "codacreditnoteview [#{ORG_PREFIX}codacreditnoteview]"
$ffa_vf_page_coda_cashentry_edit = "codacashentryedit [#{ORG_PREFIX}codacashentryedit]"
$ffa_vf_page_coda_cashentry_new = "codacashentrynew [#{ORG_PREFIX}codacashentrynew]"
$ffa_vf_page_coda_cashentry_view = "codacashentryview [#{ORG_PREFIX}codacashentryview]"
$ffa_vf_page_coda_journal_edit = "codajournaledit [#{ORG_PREFIX}codajournaledit]"
$ffa_vf_page_coda_journal_new = "codajournalnew [#{ORG_PREFIX}codajournalnew]"
$ffa_vf_page_coda_journal_view = "codajournalview [#{ORG_PREFIX}codajournalview]"
###############################################################################
# Custom tab visual force pages
###############################################################################
$ffa_vf_custom_tab_basedatajob = "baseDataManage [BaseDataJob]"
#############################
# CIF Visual Force Pages
#############################
$ffa_vf_page_coda_custom_invoice_edit = "Custom Form - Sales Invoice - New/Edit [#{ORG_PREFIX}cfsalesinvoiceedit]"
$ffa_vf_page_coda_custom_invoice_new =  "Custom Form - Sales Invoice - New/Edit [#{ORG_PREFIX}cfsalesinvoiceedit]"
$ffa_vf_page_coda_custom_invoice_view = "Custom Form - Sales Invoice - View [#{ORG_PREFIX}cfsalesinvoiceview]"
$ffa_vf_page_coda_custom_credit_note_edit = "Custom Form - Sales Credit Note - New/Edit [#{ORG_PREFIX}cfsalescreditnoteedit]"
$ffa_vf_page_coda_custom_credit_note_new =  "Custom Form - Sales Credit Note - New/Edit [#{ORG_PREFIX}cfsalescreditnoteedit]"
$ffa_vf_page_coda_custom_credit_note_view = "Custom Form - Sales Credit Note - View [#{ORG_PREFIX}cfsalescreditnoteview]"
$ffa_vf_page_coda_custom_payable_invoice_edit = "Custom Form - Payable Invoice - New/Edit [#{ORG_PREFIX}cfpurchaseinvoiceedit]"
$ffa_vf_page_coda_custom_payable_invoice_new =  "Custom Form - Payable Invoice - New/Edit [#{ORG_PREFIX}cfpurchaseinvoiceedit]"
$ffa_vf_page_coda_custom_payable_invoice_view = "Custom Form - Payable Invoice - View [#{ORG_PREFIX}cfpurchaseinvoiceview]"
$ffa_vf_page_coda_custom_purchase_credit_note_edit = "Custom Form - Payable Credit Note - New/Edit [#{ORG_PREFIX}cfpurchasecreditnoteedit]"
$ffa_vf_page_coda_custom_purchase_credit_note_new =  "Custom Form - Payable Credit Note - New/Edit [#{ORG_PREFIX}cfpurchasecreditnoteedit]"
$ffa_vf_page_coda_custom_purchase_credit_note_view = "Custom Form - Payable Credit Note - View [#{ORG_PREFIX}cfpurchasecreditnoteview]"
$ffa_vf_page_coda_custom_journal_edit = "Custom Form - Journal - New/Edit [#{ORG_PREFIX}cfjournaledit]"
$ffa_vf_page_coda_custom_journal_new =  "Custom Form - Journal - New/Edit [#{ORG_PREFIX}cfjournaledit]"
$ffa_vf_page_coda_custom_journal_view = "Custom Form - Journal - View [#{ORG_PREFIX}cfjournalview]"
$ffa_vf_page_coda_custom_cash_entry_edit = "Custom Form - Cash Entry - New/Edit [#{ORG_PREFIX}cfcashentryedit]"
$ffa_vf_page_coda_custom_cash_entry_new =  "Custom Form - Cash Entry - New/Edit [#{ORG_PREFIX}cfcashentryedit]"
$ffa_vf_page_coda_custom_cash_entry_view = "Custom Form - Cash Entry - View [#{ORG_PREFIX}cfcashentryview]"



##################################################
# edit view
##################################################
$view_element_list = "#colselector_select_0>option"
$view_element_selected_fields_list = "#colselector_select_1>option"
$view_right_arrow_icon = "#colselector_select_0_right>img"
$view_left_arrow_icon = "#colselector_select_0_left>img"
$view_option_field_name_pattern = "#colselector_select_0>option:nth-of-type("+$sf_param_substitute+")"
$view_option_selected_field_name_pattern = "#colselector_select_1>option:nth-of-type("+$sf_param_substitute+")"
$view_name_input = "input[id='fname']"
$view_unique_name_input = "input[id='devname']"
###################################################
# FFA Profile
###################################################
$ffa_profile_system_administrator = "System Administrator"
$ffa_profile_sales_invoicing_clerk= "FinancialForce Sales Invoicing Clerk"
$ffa_profile_standard_user = "Standard User"
###################################################
# Locale name
###################################################
$locale_english_united_kingdom = "English (United Kingdom)"
###################################################
# Permission Sets
###################################################
$ffa_permission_set_acc_billing_sales_invoice = "Accounting and Billing - Sales Invoice"
$ffa_permission_set_acc_billing_select_company = "Accounting and Billing - Select Company"
$ffa_permission_set_acc_billing_sales_invoice_save = "Accounting and Billing - Sales Invoice - Save"
$ffa_permission_set_acc_billing_sales_invoice_edit = "Accounting and Billing - Sales Invoice - Edit"
$ffa_permission_set_acc_billing_sales_invoice_post = "Accounting and Billing - Sales Invoice - Post"
$ffa_permission_set_accounting = "Accounting"
$ffa_permission_set_billing = "Accounting and Billing"
$ffa_permission_set_acc_billing_background_posting = "Accounting and Billing - Background Posting"
$ffa_permission_set_acc_billing_background_posting_run_now = "Accounting and Billing - Background Posting - Run Now"
$ffa_permission_set_action_views_reporting = "Action Views Reporting"
$ffa_permission_set_action_views_reporting_integration_run = "Action Views Reporting - Run"
$ffa_community_permission_fm_community = "FM Community"
$ffa_permission_set_acc_billing_user_companies = "Accounting and Billing - User Companies"
$ffa_permission_set_acc_billing_allocation_rules_save_edit = "Accounting and Billing - Allocations - Rules Save and Edit"
$ffa_permission_set_acc_billing_statiscal_basis_save_edit = "Accounting and Billing - Statistical Basis - Save and Edit"
$ffa_permission_set_acc_billing_allocations = "Accounting and Billing - Allocations"
###################################################
# Locale name
###################################################
$locale_english_united_kingdom = "English (United Kingdom)"
###################################################
# User Interface
###################################################
$user_interface_enable_related_list_hover_link_option = "Enable Related List Hover Links"
$user_interface_enable_separated_loading_of_related_list_option = "Enable Separate Loading of Related Lists"
###################################################
# License Name
###################################################
$financial_force_reporting_license = "FinancialForce Reporting"
$financial_force_accounting_license = "FinancialForce Accounting"
$financial_force_erp_core_license = "FinancialForce ERP Core"
# For lightning org, override locators with values as in lightning org
if (SF.org_is_lightning)
	$tab_all_tabs_locator = "img[alt='View Profile']"
	$page_grid_columns = "div[class='active oneContent'] div[class*='listViewContent'] div table thead tr th"
	$page_vf_table_rows = "div[class='active oneContent'] div[class*='listViewContent'] div table tbody tr"
    $page_grid_edit_link_pattern = "div[class='active oneContent'] div[class*='listViewContent'] div table tbody tr:nth-of-type("+$sf_param_substitute+") td div a"
	$page_grid_row_pattern = $page_vf_table_rows + ":nth-of-type("+$sf_param_substitute+") " +"td:nth-of-type("+$sf_param_substitute+")"
	$page_title_payments_home = "Payments | Salesforce"
	$page_grid_row_checkbox = "//a[text()='"+$sf_param_substitute+"']/ancestor::tr[1]/td[2]/span/label/span[1]"
	$page_grid_select_checkbox_pattern = "div[class*='listViewContent'] table[data-aura-class='uiVirtualDataTable'] tbody tr:nth-of-type("+$sf_param_substitute+") td:nth-of-type(2) span label span:nth-of-type(1)"
	$ffa_object_dataview_field_locator = "//span[text()='ffr__DataViewField__c']/ancestor::tr[1]/th[1]/a"
	$page_title_sales_invoices_list_view_all = "All | Salesforce"
end
